-- Switch to a database
USE MySqlDb;

-- Create partitioned table
CREATE TABLE MySqlTable (
  PrimaryKey INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RandomInt INT NOT NULL,
  RandomFloat FLOAT NOT NULL)
PARTITION BY RANGE(PrimaryKey)(
  PARTITION first VALUES LESS THAN (500000),
  PARTITION second VALUES LESS THAN MAXVALUE);

-- Populate table
SET @StartValue = 1,
    @EndValue = 10;
SET @Range = @EndValue - @StartValue + 1;
INSERT INTO MySqlTable(RandomInt, RandomFloat)
SELECT RAND() * @Range + @StartValue, RAND() * @Range + @StartValue
  FROM (
    SELECT 0 `col`
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
    UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) `tbl1`, (
    SELECT 0 `col`
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
    UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) `tbl2`, (
    SELECT 0 `col`
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
    UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) `tbl3`, (
    SELECT 0 `col`
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
    UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) `tbl4`, (
    SELECT 0 `col`
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
    UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) `tbl5`, (
    SELECT 0 `col`
    UNION SELECT 1 UNION SELECT 2 UNION SELECT 3
    UNION SELECT 4 UNION SELECT 5 UNION SELECT 6
    UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) `tbl6`;

-- Enable logging to see PolyBase commands
SET GLOBAL log_output = 'TABLE';
SET GLOBAL general_log = 'ON';

-- View commands executed by PolyBase
SELECT event_time, CONVERT(argument USING utf8) as command FROM mysql.general_log ORDER BY 1;
