-- Verify database status
\status

-- Create partitioned table
CREATE SCHEMA "SapSchema";
SET SCHEMA "SapSchema";
CREATE TABLE "SapTable" (
  "PrimaryKey" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "RandomInt" INTEGER,
  "RandomFloat" REAL,
  PRIMARY KEY("PrimaryKey", "RandomInt"))
PARTITION BY RANGE ("RandomInt") (
  PARTITION 1 <= VALUES < 6,
  PARTITION 6 <= VALUES < 11);

-- Populate table
DO
BEGIN
  DECLARE NumberOfRows INTEGER := 1000000;
  DECLARE StartValue INTEGER := 1;
  DECLARE EndValue INTEGER := 10;
  DECLARE Range INTEGER := EndValue - StartValue + 1;
  INSERT INTO "SapTable"("RandomInt", "RandomFloat")
  SELECT TOP :NumberOfRows RAND() * :Range + :StartValue, RAND() * :Range + :StartValue
    FROM _SYS_REPO.ACTIVE_OBJECT a
    JOIN _SYS_REPO.ACTIVE_OBJECT b ON b.OBJECT_NAME = a.OBJECT_NAME;
END;

-- Enable tracing to view PolyBase commands
ALTER SYSTEM ALTER CONFIGURATION ('indexserver.ini', 'SYSTEM') SET ('sqltrace', 'trace') = 'ON' WITH RECONFIGURE;
ALTER SYSTEM ALTER CONFIGURATION ('indexserver.ini', 'SYSTEM') SET ('sqltrace', 'level') = 'ALL' WITH RECONFIGURE;
