-- Connect to database
connect to DB2DB;

-- Increase transaction log
UPDATE DB CFG FOR DB2DB USING LOGSECOND 88 IMMEDIATE;

-- Create partitioned table
CREATE TABLE DB2Table(
  PrimaryKey INT GENERATED BY DEFAULT AS IDENTITY,
  RandomInt INT,
  RandomFloat REAL,
  PRIMARY KEY (PrimaryKey))
PARTITION BY (RandomInt)(
  PARTITION 1 STARTING (1) ENDING AT (5),
  PARTITION 2 STARTING (6) ENDING AT (10));

-- Populate table
INSERT INTO DB2Table(RandomInt, RandomFloat)
  WITH DT(ENO) AS (VALUES(1) UNION ALL SELECT ENO+1 FROM DT WHERE ENO < 1000000)
SELECT RAND() * 10 + 1, RAND() * 10 + 1 FROM DT;
COMMIT;

-- Enable logging to view PolyBase commands
CREATE EVENT MONITOR myactevmon
   FOR ACTIVITIES
 WRITE TO TABLE;
SET EVENT MONITOR myactevmon STATE 1;
ALTER SERVICE CLASS sysdefaultsubclass
UNDER sysdefaultuserclass
COLLECT ACTIVITY DATA
  ON ALL DATABASE PARTITIONS
WITH DETAILS AND VALUES;

-- View PolyBase executed queries
SELECT EVENT_TIMESTAMP, STMT_TEXT FROM ACTIVITYSTMT_myactevmon ORDER BY EVENT_TIMESTAMP;
